package com.aegean.icsd.mciobjects.pieces.beans;

import com.aegean.icsd.engine.core.annotations.DataProperty;
import com.aegean.icsd.engine.core.annotations.Entity;
import com.aegean.icsd.engine.core.annotations.Id;
import com.aegean.icsd.engine.generator.beans.BaseGameObject;

@Entity(Piece.NAME)
public class Piece extends BaseGameObject {
  public static final String NAME = "Piece";

  @Id(autoGenerated = true)
  @DataProperty("hasId")
  private String id;

  @Override
  public String getId() {
    return id;
  }

  @Override
  public void setId(String id) {
    this.id = id;
  }
}
