package com.aegean.icsd.mciobjects.sounds.beans;

import com.aegean.icsd.engine.core.annotations.DataProperty;
import com.aegean.icsd.engine.core.annotations.Entity;
import com.aegean.icsd.engine.core.annotations.Id;
import com.aegean.icsd.engine.common.beans.BaseGameObject;

@Entity(Sound.NAME)
public class Sound extends BaseGameObject {
  public static final String NAME = "Sound";

  @Id(autoGenerated = true)
  @DataProperty("hasId")
  private String id;

  @DataProperty("hasAssetPath")
  private String path;

  @DataProperty("isImageAssociated")
  private Boolean imageAssociated;

  public String getPath() {
    return path;
  }

  public void setPath(String path) {
    this.path = path;
  }

  public void setImageAssociated(Boolean imageAssociated) {
    this.imageAssociated = imageAssociated;
  }

  public Boolean isImageAssociated() {
    return this.imageAssociated;
  }

  @Override
  public void setId(String id) {
    this.id = id;
  }

  @Override
  public String getId() {
    return this.id;
  }
}
