package com.aegean.icsd.mciobjects.questions.beans;

import com.aegean.icsd.engine.common.beans.Difficulty;
import com.aegean.icsd.engine.core.annotations.DataProperty;
import com.aegean.icsd.engine.core.annotations.Entity;
import com.aegean.icsd.engine.core.annotations.Id;
import com.aegean.icsd.engine.generator.beans.BaseGameObject;

@Entity(Question.NAME)
public class Question extends BaseGameObject {
  public static final String NAME = "Question";

  @Id(autoGenerated = true)
  @DataProperty("hasId")
  private String id;

  @DataProperty("hasDifficulty")
  private Difficulty difficulty;

  @DataProperty("hasQuestionDescription")
  private String description;

  @DataProperty("isImageQuestion")
  private Boolean imageQuestion;

  @DataProperty("isTextQuestion")
  private Boolean textQuestion;

  public void setDifficulty(Difficulty difficulty) {
    this.difficulty = difficulty;
  }

  public Difficulty getDifficulty() {
    return this.difficulty;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public String getDescription() {
    return this.description;
  }

  public void setImageQuestion(Boolean imageQuestion) {
    this.imageQuestion = imageQuestion;
  }

  public Boolean isImageQuestion() {
    return this.imageQuestion;
  }

  public void setTextQuestion(Boolean textQuestion) {
    this.textQuestion = textQuestion;
  }

  public Boolean isTextQuestion() {
    return this.textQuestion;
  }

  @Override
  public void setId(String id) {
    this.id = id;
  }

  @Override
  public String getId() {
    return this.id;
  }
}
