package com.aegean.icsd.mciobjects.observationobjs.beans;

import com.aegean.icsd.engine.core.annotations.DataProperty;
import com.aegean.icsd.engine.core.annotations.Entity;
import com.aegean.icsd.engine.core.annotations.Id;
import com.aegean.icsd.engine.generator.beans.BaseGameObject;

@Entity(ObservationObj.NAME)
public class ObservationObj extends BaseGameObject {
  public static final String NAME = "ObservationObj";

  @Id(autoGenerated = true)
  @DataProperty("hasId")
  private String id;

  @DataProperty("hasTotalImages")
  private Integer nbOfImages;

  @Override
  public String getId() {
    return id;
  }

  @Override
  public void setId(String id) {
    this.id = id;
  }

  public Integer getNbOfImages() {
    return nbOfImages;
  }

  public void setNbOfImages(Integer nbOfImages) {
    this.nbOfImages = nbOfImages;
  }

}
