package com.aegean.icsd.mciobjects.blocks.beans;

import java.util.List;

import com.aegean.icsd.engine.core.annotations.DataProperty;
import com.aegean.icsd.engine.core.annotations.Entity;
import com.aegean.icsd.engine.core.annotations.Id;
import com.aegean.icsd.engine.generator.beans.BaseGameObject;

@Entity(BlockSet.NAME)
public class BlockSet extends BaseGameObject {
  public static final String NAME = "BlockSet";

  @Id(autoGenerated = true)
  @DataProperty("hasId")
  private String id;

  @DataProperty("hasOrder")
  private Integer order;

  private List<Block> blocks;

  private List<Block> movingBlocks;

  public List<Block> getBlocks() {
    return blocks;
  }

  public void setBlocks(List<Block> blocks) {
    this.blocks = blocks;
  }

  public Integer getOrder() {
    return order;
  }

  public void setOrder(Integer order) {
    this.order = order;
  }

  public List<Block> getMovingBlocks() {
    return movingBlocks;
  }

  public void setMovingBlocks(List<Block> movingBlocks) {
    this.movingBlocks = movingBlocks;
  }
}
