package com.aegean.icsd.mciobjects.blocks.beans;

import com.aegean.icsd.engine.core.annotations.DataProperty;
import com.aegean.icsd.engine.core.annotations.Entity;
import com.aegean.icsd.engine.core.annotations.Id;
import com.aegean.icsd.engine.generator.beans.BaseGameObject;

@Entity(BlockSet.NAME)
public class BlockSet extends BaseGameObject {
  public static final String NAME = "BlockSet";

  @Id(autoGenerated = true)
  @DataProperty("hasId")
  private String id;
}
