package com.aegean.icsd.mciobjects.blocks.beans;

import com.aegean.icsd.engine.core.annotations.DataProperty;
import com.aegean.icsd.engine.core.annotations.Entity;
import com.aegean.icsd.engine.core.annotations.Id;

@Entity(NumberBlock.NAME)
public class NumberBlock extends Block {
  public static final String NAME = "NumberBlock";

  @Id(autoGenerated = true)
  @DataProperty("hasId")
  private String id;

  @DataProperty("hasNumberValue")
  private Long numberValue;

  @Override
  public String getId() {
    return id;
  }

  @Override
  public void setId(String id) {
    this.id = id;
  }

  public Long getNumberValue() {
    return numberValue;
  }

  public void setNumberValue(Long numberValue) {
    this.numberValue = numberValue;
  }

}
